#pragma once

#include <QDialog>
#include "ui_Settings.h"

/*
###########################################################################################################
#
#		Auto-generated by Qt's widget maker. Simply makes it less of a pain-in-the-a** to set up windows.
#
#		All that has been generated are the class's `public` and `private` section—the latter remains empty
#
###########################################################################################################
*/

class Settings : public QDialog, public Ui::SettingsClass
{
	Q_OBJECT

public:
	Settings(QWidget *parent = nullptr);
	~Settings();

private:
private slots:
	void on_botCheckBox_stateChanged(int state);
};
